### ISSUE TITLE
Getting a bootloop after installing the module - tzdata 2020D

### ISSUE THREAD

**Issue by aharisi** [Magisk-Modules-Repo/Systemless_TZData#14] opened 2020-12-04 19:00 UTC
Running Magisk 21.1, LineageOS 16.0. I can provide a log if you want.

-- A.

**Comment by RyanHakurei** [comment] 2020-12-04 22:51
Yes please do, for now if you can revert to the previous copy of the module. If you can't I've reverted a recent PR so you should be able to re-download a known working copy.

**Comment by aharisi** [comment] 2020-12-05 00:06
[log.txt](https://github.com/Magisk-Modules-Repo/Systemless_TZData/files/5646112/log.txt)

**Comment by RyanHakurei** [comment] 2020-12-05 03:22
Yeah, your ROM doesn't like the updated tzdata for some reason.

```
12-04 18:45:20.930  2095  2095 E Zygote  : System zygote died with exception
12-04 18:45:20.930  2095  2095 E Zygote  : java.lang.NullPointerException: Attempt to invoke virtual method 'libcore.io.BufferIterator libcore.io.MemoryMappedFile.bigEndianIterator()' on a null object reference
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.ZoneInfoDB$TzData.getBufferIterator(ZoneInfoDB.java:161)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.ZoneInfoDB$TzData.makeTimeZoneUncached(ZoneInfoDB.java:305)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.ZoneInfoDB$TzData$1.create(ZoneInfoDB.java:100)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.ZoneInfoDB$TzData$1.create(ZoneInfoDB.java:96)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at libcore.util.ZoneInfoDB$TzData.makeTimeZone(ZoneInfoDB.java:358)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1110)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.text.format.Time$TimeCalculator.<init>(Time.java:1070)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.text.format.Time.initialize(Time.java:208)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.text.format.Time.<init>(Time.java:184)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at org.lineageos.platform.internal.display.TwilightTracker$LocationHandler.retrieveLocation(TwilightTracker.java:317)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at org.lineageos.platform.internal.display.TwilightTracker$LocationHandler.handleMessage(TwilightTracker.java:251)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at android.os.Looper.loop(Looper.java:193)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at com.android.server.SystemServer.run(SystemServer.java:480)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at com.android.server.SystemServer.main(SystemServer.java:302)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at java.lang.reflect.Method.invoke(Native Method)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
12-04 18:45:20.930  2095  2095 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
12-04 18:45:20.930  2095  2095 D AndroidRuntime: Shutting down VM
12-04 18:45:20.930  2095  2095 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-04 18:45:20.930  2095  2095 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'libcore.io.BufferIterator libcore.io.MemoryMappedFile.bigEndianIterator()' on a null object reference
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.ZoneInfoDB$TzData.getBufferIterator(ZoneInfoDB.java:161)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.ZoneInfoDB$TzData.makeTimeZoneUncached(ZoneInfoDB.java:305)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.ZoneInfoDB$TzData$1.create(ZoneInfoDB.java:100)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.ZoneInfoDB$TzData$1.create(ZoneInfoDB.java:96)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at libcore.util.ZoneInfoDB$TzData.makeTimeZone(ZoneInfoDB.java:358)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1110)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.text.format.Time$TimeCalculator.<init>(Time.java:1070)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.text.format.Time.initialize(Time.java:208)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.text.format.Time.<init>(Time.java:184)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at org.lineageos.platform.internal.display.TwilightTracker$LocationHandler.retrieveLocation(TwilightTracker.java:317)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at org.lineageos.platform.internal.display.TwilightTracker$LocationHandler.handleMessage(TwilightTracker.java:251)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:480)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:302)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
12-04 18:45:20.930  2095  2095 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
12-04 18:45:20.937  2095  2142 D ActivityManager: Finishing user boot 0
```

If you will for me, delete the copy of the module you have now, redownload it from Magisk, and reflash it and see if you continue to bootloop.

**Comment by aharisi** [comment] 2020-12-05 03:36
Did that and no more bootloop with this version...

**Comment by RyanHakurei** [comment] 2020-12-05 04:06
Cool. I will have a test module for you hopefully tomorrow to see if you continue to bootloop. If you don't mind testing it that is.

**Comment by gjf** [comment] 2020-12-12 19:46
Just wonder where did you get 2020D having 2020A as a last version in this repo?

**Comment by RyanHakurei** [comment] 2020-12-13 02:19
Someone submitted a PR and after looking over it and finding no obvious issues I accepted it. My guess is his tzdata file was corrupt.

Upon checking the AOSP repo 2020D is the latest version and I have that test zip here if you want to try it:
https://files.catbox.moe/w8p597.zip

**Comment by nkh0472** [comment] 2020-12-23 09:51
I am the person who submitted that PR.

At that time, I only tested that on MIUI 12.0.4, and there was no strange thing happen.
However, after I see your issue hours ago, I tested it on Lineage OS 16.0, and I reproduced the bug.

I'm not sure why does it happen, but I'm quite sure the file is the same on [android Git repositories - Git at Google](https://android.googlesource.com/platform/system/timezone/). And I just cloned this repo again using `git clone https://android.googlesource.com/platform/system/timezone`, the hashes between two tzdata files is the same.

Since the source is applicable to the latest source code of Google, I guess it might not be compatible with the version of Android 10(?).

No matter what, the 2020e release of the tz code and data is available about 7 hours ago. After Google releases their new tzdata file (normally after IANA's released them 1~3 days), I'll test it on Lineage OS 16.0 again to verify my guess. If it will not work then, I don't know what to do…

**Comment by nkh0472** [comment] 2020-12-23 09:53
I apologize for the trouble and inconvenience caused by me.

**Comment by nkh0472** [comment] 2020-12-23 13:08
After reading commit logs in https://android.googlesource.com/platform/system/timezone/, I thought I found a possible breaking change. But I'm not sure the crash on Lineage OS 16.0 is caused by this:

[Remove zone.tab from tzdata](https://android.googlesource.com/platform/system/timezone/+/61b7d56237cbf94d8d7a1779427b1b79ed63cf12)

As we can see, this commit is between 2020a and 2020b.

> ddd4b75 Update Android from 2020c to 2020d by Neil Fuller · 9 weeks ago
> 6b37f04 Update Android from 2020b to 2020c by Neil Fuller · 9 weeks ago
> 633367f Update Android from 2020a to 2020b by Neil Fuller · 2 months ago
> **61b7d56 Remove zone.tab from tzdata by Neil Fuller · 7 months ago**
> 4da0af1 Tweak the tzdata format for future changes by Neil Fuller · 7 months ago
> a2d7034 Update Android to tzdb 2020a by Neil Fuller · 8 months ago
> c0e5db0 Update tzdb version from 2019b to 2019c by Neil Fuller · 1 year, 3 months ago

The commit description is as follows:

> **The zone.tab information is not used on Android so can be**
> **removed**, saving 20KB in storage (and in Java heap).
> 
> NOTE TO OTHER ANDROID TIME ZONE MAINTAINERS:
> **This is not a backwards compatible change.** tzdata files should
> not be copied to earlier or later releases. Use update-tzdata.py from
> the branch you are maintaining to create the binary files for that
> branch.
> 
> Bug: 161699306
> Test: update-tzdata.py
> Test: Ran dump-tzdata.py
> Change-Id: [I6c79e9d2b9ef16679cacfb6ce4f011bfbb96faba](https://android-review.googlesource.com/#/q/I6c79e9d2b9ef16679cacfb6ce4f011bfbb96faba)

According to the description "this is not a backwards compatible change", does it means this module cannot be applying to a newer version like Android 11?

**Comment by nkh0472** [comment] 2020-12-23 14:54
See here: https://github.com/Magisk-Modules-Repo/Systemless_TZData/pull/17#issuecomment-750333518

> After reading many commit on various AOSP branches, I realized it is extremely important to give such a warning.
> Because tzdata is always Android-branch-relative, and there's no way to guarantee this module's compatibility on a specific Android system.
> Similar warnings have appeared several times in AOSP's commit logs. An example is as follows:
> https://android.googlesource.com/platform/system/timezone/+/bca6f6ff048010d06955deaacfa47f1ea372460d
> 
> DO NOT MERGE: Update tzdb version from 2019b to 2019c
> 
> Update tzdb version from 2019b to 2019c [Q branch].
> 
> Notes for Android time zone maintainers:
> Like all tzdb updates, the binary files in this commit should not be
> patched to other branches: they are not guaranteed to work. Also note
> that there are associated changes in external/cldr, external/icu and
> often others that should also be applied. tzdb updates are incremental
> changes: all previous tzdb updates should be applied. Look for
> aosp/-dev changes for backports. If you have a local branch
> with ICU changes the ICU .dat file in external/icu will not apply
> cleanly. Instead, make equivalent changes to text files and run
> system/timezone/update-tzdata.py.
> ……

**Comment by RyanHakurei** [comment] 2020-12-23 19:31
I will apply your PR locally and play around with some ROMs to see what the best solution is going forward.

**Comment by gjf** [comment] 2020-12-24 14:18
> Upon checking the AOSP repo 2020D is the latest version and I have that test zip here if you want to try it:
> https://files.catbox.moe/w8p597.zip

Just to let you know this zip works OK on Oneplus 7T Pro running OxygenOS (Android 10).

**Comment by nkh0472** [comment] 2020-12-24 15:24
> > Upon checking the AOSP repo 2020D is the latest version and I have that test zip here if you want to try it:
> > https://files.catbox.moe/w8p597.zip
> 
> Just to let you know this zip works OK on Oneplus 7T Pro running OxygenOS (Android 10).

My commit for 2020d is exactly downloaded from the AOSP repo, and I've checked the hash to verify its integrity. It works fine on Android 10 (MIUI 12.0.5), but not on Android 9 (Lineage OS 16.0). I guess there must have some breaking changes in it.

Version compatibility is a big problem that we can't ignore. Although 2020e has already been released by IANA, I thought we have to compile different versions to fit different versions of Android. Besides, writing a new install script is another difficulty.

However, the most strange part of the whole thing is that no one seems to have complained about the failure of the module before. Can we say that the compatibility problems in versions before Android 10 were caused by the single commit between 2020a and 2020b? If that is true, the only thing we need to do is download the compile script in 2020a, then just use it to compile tzdata for 2020e. I don't know if this will bring potential compatibility problems to Android 11. But so far, it's the most important thing for this module to run both on Android 10 and previous systems.

I'll have more free time in about five days, and then I'll try the compatibility of 2020b on Android 9. At present, it is known that 2020A can be used, and if 2020b can not be used at that time, it can be determined that the problem is in that commit I mentioned before.

> > ddd4b75 Update Android from 2020c to 2020d by Neil Fuller · 9 weeks ago
> > 6b37f04 Update Android from 2020b to 2020c by Neil Fuller · 9 weeks ago
> > 633367f Update Android from 2020a to 2020b by Neil Fuller · 2 months ago
> > **61b7d56 Remove zone.tab from tzdata by Neil Fuller · 7 months ago** [LINK](https://android.googlesource.com/platform/system/timezone/+/61b7d56237cbf94d8d7a1779427b1b79ed63cf12)
> > 4da0af1 Tweak the tzdata format for future changes by Neil Fuller · 7 months ago
> > a2d7034 Update Android to tzdb 2020a by Neil Fuller · 8 months ago
> > c0e5db0 Update tzdb version from 2019b to 2019c by Neil Fuller · 1 year, 3 months ago
> 
> The commit description is as follows:
> 
> > **The zone.tab information is not used on Android so can be**
> > **removed**, saving 20KB in storage (and in Java heap).
> > NOTE TO OTHER ANDROID TIME ZONE MAINTAINERS:
> > **This is not a backwards compatible change.** tzdata files should
> > not be copied to earlier or later releases. Use update-tzdata.py from
> > the branch you are maintaining to create the binary files for that
> > branch.
> > Bug: 161699306
> > Test: update-tzdata.py
> > Test: Ran dump-tzdata.py
> > Change-Id: [I6c79e9d2b9ef16679cacfb6ce4f011bfbb96faba](https://android-review.googlesource.com/#/q/I6c79e9d2b9ef16679cacfb6ce4f011bfbb96faba)

**Comment by RyanHakurei** [comment] 2020-12-24 15:53
The best solution for now might be to add a zip for Android 9 and below users in the readme, I can change the version code to be so high that hopefully Magisk won't see any new version as an update and a user won't accidentally update and bootloop themselves.

**Comment by gjf** [comment] 2020-12-24 18:36
> The best solution for now might be to add a zip for Android 9 and below users in the readme, I can change the version code to be so high that hopefully Magisk won't see any new version as an update and a user won't accidentally update and bootloop themselves.

Just to understand the situation: do you mean tzdata should be different for different Android version?
If so, this issue can be easily solved in Magisk installer itself.
Please share me different zips for different versions and I will try to help if you please.

**Comment by nkh0472** [comment] 2021-01-09 03:04
2020f tzdata in AOSP repo just released 35 hours ago. 
https://android.googlesource.com/platform/system/timezone/+/b85cbdff44f89a38d8e85708524d361d32516818

>Just to understand the situation: do you mean tzdata should be different for different Android version?

So far, that's true. I haven't compiled the old format of tzdata for 2020f yet. You can make a test module using both 2020a (in this repo) which for android 9 and below and [2020f (in my repo)](https://github.com/nkh0472/Systemless_TZData/tree/2020f-for-Android-10) for Android 10.

**Comment by gjf** [comment] 2021-01-09 12:48
You can easily build a single module with toggling depending on SDK version. Something like
`osver_fn() {
DEVFND=0
SDK_VER=23
SDK_VER_MAX=29
  if [ $API -ge $SDK_VER ] && [ $API -lt $SDK_VER_MAX ]; then
    ui_print "SDK$API detected. It is supported."
    DEVFND=1
    break
  fi
if [ $DEVFND == 0 ]; then
  abort "Android is older than Android 6, newer than Android 9 or modified build.prop! Aborting."
fi`
I've made this code for my own purposes but you can change it to toggle tzdata version for Android <10 and Android >=10 (SDK<29 or SDK>=29).

**Comment by gjf** [comment] 2021-01-09 18:02
OK, I did the job: here is a fork that detects a proper version of Android and installs a proper file: https://github.com/gjf/Systemless_TZData

Please note I have implemented an exit when Android>11 (because it was not tested) or when SDK cannot be checked using Magisk mechanism (it is possible in dirty custom ROMs). It will avoid possible bootloops.

Also the template was adopted to latest version of Magisk - unnecessary files were deleted.

You can clone it and use it for future updates.

And of course - thank you for maintaining this module!

**Comment by nkh0472** [comment] 2021-01-10 00:28
Good job. I'll test it tomorrow.

Also, I've created a pull request for template cleaning. See it here:
https://github.com/Magisk-Modules-Repo/Systemless_TZData/pull/16

**Comment by RyanHakurei** [comment] 2021-01-10 01:40
@nkh0472 + @gjf Once it's tested and you've verified it's working submit a PR and I will review and merge it. I have been out of action due to my test device experiencing a swollen battery and the replacement is taking a long while to get to me.

**Comment by gjf** [comment] 2021-01-10 14:42
I have tested it on both OnePlus 7T Pro (Android 10) and Samsung Galaxy Note 10.1 LTE (Android 5). All seems working.
Pull request was also created.

**Comment by RyanHakurei** [comment] 2021-01-11 09:01
I have merged @gjf's PR, if anyone here expirences any issues feel free to re-open this issue. Thank you all for your work, I wish I could have been more active but as I said my test device has been out of action.

**Closed as completed by RyanHakurei** 2021-01-11 09:01 UTC
Labels: bug
